language: c
before_install:
  - export ARDUINO_VERSION=1.6.5
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_1.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :1 -ac -screen 0 1280x1024x16"
  - sleep 3
  - export DISPLAY=:1.0
  - wget http://downloads.arduino.cc/arduino-${ARDUINO_VERSION}-linux64.tar.xz
  - tar xf arduino-${ARDUINO_VERSION}-linux64.tar.xz
  - sudo mv arduino-${ARDUINO_VERSION} /usr/local/share/arduino
  - sudo ln -s /usr/local/share/arduino/arduino /usr/local/bin/arduino
install:
  - ln -s ${PWD} /usr/local/share/arduino/libraries/I2cDiscreteIoExpander
  - arduino --pref "compiler.warning_level=all" --save-prefs
script:
  - echo $PWD
  - echo $HOME
  - ls -al $PWD
  - source ${TRAVIS_BUILD_DIR}/travis/common.sh
  - build_examples
