language: python

python:
  - 2.7

sudo: false

cache:
  directories:
    - ~/.platformio

# include one array element for each sketch in examples/
env:
  - PLATFORMIO_CI_SRC=examples/BareMinimum/BareMinimum.ino
  - PLATFORMIO_CI_SRC=examples/MultipleDevices/MultipleDevices.ino

install:
  - pip install -U platformio

script:
  - env
  - echo $HOME
  - echo $TRAVIS_BUILD_DIR
  - ls -al $PWD
  - platformio ci                 # at least one board from each platform
    --board=uno                   # atmelavr
    --board=due                   # atmelsam
    --board=huzzah                # espressif8266
    --board=genuino101            # intel_arc32
    --board=teensy31              # teensy
    --lib=.
    ${PLATFORMIO_CI_SRC}
